#!/bin/bash

# Font
FONT1="lemon-10"

# bar alignment 
BW=1420
BH=18
BX=1930
BY=0

# Color directory
CD="$HOME/etc/colors/vanilla"

#TBG=#001a1a1a
BG=`cat ${CD} | grep -i background: | tail -c 8`
FG=`cat ${CD} | grep -i foreground: | tail -c 8`

# black !
C00=`cat ${CD} | grep -i color0: | tail -c 8`                                                 
C08=`cat ${CD} | grep -i color8: | tail -c 8`

# red !
C01=`cat ${CD} | grep -i color1: | tail -c 8`
C09=`cat ${CD} | grep -i color9: | tail -c 8`

# green !
C02=`cat ${CD} | grep -i color2: | tail -c 8`
C10=`cat ${CD} | grep -i color10: | tail -c 8`

# yellow !
C03=`cat ${CD} | grep -i color3: | tail -c 8`
C11=`cat ${CD} | grep -i color11: | tail -c 8`

# blue !
C04=`cat ${CD} | grep -i color4: | tail -c 8`
C12=`cat ${CD} | grep -i color12: | tail -c 8`

# magenta !
C05=`cat ${CD} | grep -i color5: | tail -c 8`
C13=`cat ${CD} | grep -i color13: | tail -c 8`

# cyan !
C06=`cat ${CD} | grep -i color6: | tail -c 8`
C14=`cat ${CD} | grep -i color14: | tail -c 8`

# white !
C07=`cat ${CD} | grep -i color7: | tail -c 8`
C15=`cat ${CD} | grep -i color15: | tail -c 8`
