xrdb -load $XDG_CONFIG_HOME/xorg/Xresources

#set fonts
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/artwiz
i
#set cursor
xsetroot -cursor_name left_ptr

#start keybindings
sxhkd &

#start composite manager
compton --config $XDG_CONFIG_HOME/xorg/compton -b &

#gief wallpaper plx
#hsetroot -fill ~/Bilder/Wallpaper/Pictures/asurei.jpg &
hsetroot -solid "#95c1c0" &  # cyan

#dual monitor setup
xrandr --output DVI-I-1 --auto --output HDMI-1 --auto --right-of DVI-I-1

#rxvt as daemon
#urxvtd &

#bar
bar &

#start mpd as user and start mpdas
mpd $XDG_CONFIG_HOME/mpd/mpd.conf && mpdas &

#damnit brokren right arm
xinput set-button-map 9 3 2 1
xset m 1/3 4

#start wm
exec 2bwm
